import { GameProvider } from "@/@types/gameProvider";

const fetchGameProviders = () => {
  const data = [
    {
      id: 3,
      provider_code: "PGSOFT",
      provider_name: "PGSoft",
      is_active: 1,
      order: 5,
      status: 1,
      game_list_status: 1,
      imgUrl: "https://agdashboard.pro/assets/img/provider_logo/pg_soft.png",
      pivot: {
        game_type_id: 2,
        product_id: 3,
        image: "pg_soft.png",
      },
    },
    {
      id: 19,
      provider_code: "R88",
      provider_name: "Rich88",
      is_active: 1,
      order: 5,
      status: 1,
      game_list_status: 1,
      imgUrl: "https://agdashboard.pro/assets/img/provider_logo/rich_88.png",
      pivot: {
        game_type_id: 2,
        product_id: 19,
        image: "rich_88.png",
      },
    },
    {
      id: 6,
      provider_code: "JDB",
      provider_name: "JDB Gaming",
      is_active: 1,
      order: 6,
      status: 1,
      game_list_status: 1,
      imgUrl: "https://agdashboard.pro/assets/img/provider_logo/JDB.png",
      pivot: {
        game_type_id: 2,
        product_id: 6,
        image: "JDB.png",
      },
    },
    {
      id: 7,
      provider_code: "CQ9",
      provider_name: "CQ9",
      is_active: 1,
      order: 7,
      status: 1,
      game_list_status: 1,
      imgUrl: "https://agdashboard.pro/assets/img/provider_logo/cq_9_slot.png",
      pivot: {
        game_type_id: 2,
        product_id: 7,
        image: "cq_9_slot.png",
      },
    },
    {
      id: 8,
      provider_code: "UUS",
      provider_name: "UUSlot",
      is_active: 1,
      order: 8,
      status: 1,
      game_list_status: 1,
      imgUrl: "https://agdashboard.pro/assets/img/provider_logo/UUslot.png",
      pivot: {
        game_type_id: 2,
        product_id: 8,
        image: "UUslot.png",
      },
    },
    {
      id: 9,
      provider_code: "MGH5",
      provider_name: "MegaH5",
      is_active: 1,
      order: 9,
      status: 1,
      game_list_status: 1,
      imgUrl: "https://agdashboard.pro/assets/img/provider_logo/MEGAH5.png",
      pivot: {
        game_type_id: 2,
        product_id: 9,
        image: "MEGAH5.png",
      },
    },
    {
      id: 10,
      provider_code: "EPW",
      provider_name: "EpicWin",
      is_active: 1,
      order: 10,
      status: 1,
      game_list_status: 1,
      imgUrl: "https://agdashboard.pro/assets/img/provider_logo/Epic_win.png",
      pivot: {
        game_type_id: 2,
        product_id: 10,
        image: "Epic_win.png",
      },
    },
    {
      id: 11,
      provider_code: "YBAT",
      provider_name: "YellowBat",
      is_active: 1,
      order: 11,
      status: 1,
      game_list_status: 1,
      imgUrl: "https://agdashboard.pro/assets/img/provider_logo/Yellow_bet.png",
      pivot: {
        game_type_id: 2,
        product_id: 11,
        image: "Yellow_bet.png",
      },
    },
    {
      id: 12,
      provider_code: "EVOPLAY",
      provider_name: "EvoPlay",
      is_active: 1,
      order: 12,
      status: 1,
      game_list_status: 1,
      imgUrl: "https://agdashboard.pro/assets/img/provider_logo/Evo_Play.png",
      pivot: {
        game_type_id: 2,
        product_id: 12,
        image: "Evo_Play.png",
      },
    },
    {
      id: 13,
      provider_code: "FACHAI",
      provider_name: "FaChai",
      is_active: 1,
      order: 13,
      status: 1,
      game_list_status: 1,
      imgUrl: "https://agdashboard.pro/assets/img/provider_logo/Fachai.png",
      pivot: {
        game_type_id: 2,
        product_id: 13,
        image: "Fachai.png",
      },
    },
  ] as GameProvider[];

  return data as GameProvider[];
};

export { fetchGameProviders };
